spring.application.name=club_managment_api

spring.datasource.url=jdbc:h2:mem:testdb



spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework=info


spring.security.user.name=Eyob
spring.security.user.password={noop}Yobil

  
  jwt.secret=	$2a$10$zA24CX1qgumck8PCojSj6u3w9eFsFKLKtHKe94oXetcmxE7iCoVc6
  jwt.expiration=3600000          # 1 hour in milliseconds
jwt.refresh-expiration=604800000 # 7 days in milliseconds